version: "2"
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - 80:8081
    volumes:
    # Note: volume ownership needs to be set to 200
      - ./volumes/nexus-data:/nexus-data
